packages:
  - packages/*
  - apps/*

catalog:
  '@base-ui/react': ^1.4.1
  '@biomejs/biome': ^2.4.14
  '@commitlint/cli': ^21.0.0
  '@commitlint/config-conventional': ^21.0.0
  '@effect/atom-react': ^4.0.0-beta.65
  '@effect/language-service': ^0.85.1
  '@effect/openapi-generator': ^4.0.0-beta.65
  '@effect/platform-node': ^4.0.0-beta.65
  '@lucas-barake/effect-form-react': ^0.24.0
  '@nktkas/hyperliquid': ^0.32.2
  '@reown/appkit': ^1.8.19
  '@reown/appkit-adapter-wagmi': ^1.8.19
  '@rolldown/plugin-babel': ^0.2.0
  '@stakekit/common': ^0.0.61
  '@tailwindcss/vite': ^4.3.0
  '@tanstack/devtools-vite': ^0.6.0
  '@tanstack/react-devtools': ^0.10.2
  '@tanstack/react-query': ^5.100.9
  '@tanstack/react-router': ^1.169.2
  '@tanstack/react-router-devtools': ^1.166.13
  '@tanstack/react-virtual': ^3.13.24
  '@tanstack/router-cli': ^1.166.43
  '@tanstack/router-plugin': ^1.167.35
  '@types/node': ^25.6.2
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.0
  '@vite-pwa/assets-generator': ^1.0.2
  '@vitejs/plugin-react': ^6.0.1
  '@vitest/browser-playwright': ^4.1.5
  babel-plugin-react-compiler: ^1.0.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  effect: ^4.0.0-beta.65
  husky: ^9.1.7
  jsdom: ^29.1.1
  lucide-react: ^1.14.0
  openapi-filter: ^3.2.3
  react: ^19.2.6
  react-dom: ^19.2.6
  sonner: ^2.0.7
  tailwind-merge: ^3.5.0
  tailwindcss: ^4.3.0
  tsx: ^4.21.0
  turbo: ^2.9.12
  tw-animate-css: ^1.3.6
  typescript: ^6.0.3
  viem: ^2.48.11
  vite: ^8.0.11
  vite-plugin-node-polyfills: ^0.26.0
  vitest: ^4.1.5
  vitest-browser-react: ^2.2.0
  wagmi: ^3.6.11

nodeLinker: hoisted
patchedDependencies:
  '@lucas-barake/effect-form-react@0.24.0': patches/@lucas-barake__effect-form-react@0.24.0.patch
  '@lucas-barake/effect-form@0.23.0': patches/@lucas-barake__effect-form@0.23.0.patch
  vite-plugin-node-polyfills@0.26.0: patches/vite-plugin-node-polyfills@0.26.0.patch
