/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountWithdrawRouteImport } from './routes/account/withdraw'
import { Route as AccountDepositRouteImport } from './routes/account/deposit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWithdrawRoute = AccountWithdrawRouteImport.update({
  id: '/account/withdraw',
  path: '/account/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDepositRoute = AccountDepositRouteImport.update({
  id: '/account/deposit',
  path: '/account/deposit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/deposit': typeof AccountDepositRoute
  '/account/withdraw': typeof AccountWithdrawRoute
  '/account': typeof AccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/deposit': typeof AccountDepositRoute
  '/account/withdraw': typeof AccountWithdrawRoute
  '/account': typeof AccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account/deposit': typeof AccountDepositRoute
  '/account/withdraw': typeof AccountWithdrawRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account/deposit' | '/account/withdraw' | '/account'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account/deposit' | '/account/withdraw' | '/account'
  id: '__root__' | '/' | '/account/deposit' | '/account/withdraw' | '/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountDepositRoute: typeof AccountDepositRoute
  AccountWithdrawRoute: typeof AccountWithdrawRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/withdraw': {
      id: '/account/withdraw'
      path: '/account/withdraw'
      fullPath: '/account/withdraw'
      preLoaderRoute: typeof AccountWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/deposit': {
      id: '/account/deposit'
      path: '/account/deposit'
      fullPath: '/account/deposit'
      preLoaderRoute: typeof AccountDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountDepositRoute: AccountDepositRoute,
  AccountWithdrawRoute: AccountWithdrawRoute,
  AccountIndexRoute: AccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
