/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountWithdrawRouteImport } from './routes/account/withdraw'
import { Route as AccountDepositRouteImport } from './routes/account/deposit'
import { Route as PositionDetailsPositionIdIndexRouteImport } from './routes/position-details/$positionId/index'
import { Route as PositionDetailsPositionIdOrderRouteImport } from './routes/position-details/$positionId/order'
import { Route as PositionDetailsPositionIdCloseRouteImport } from './routes/position-details/$positionId/close'
import { Route as AccountWithdrawSignRouteImport } from './routes/account/withdraw_/sign'
import { Route as AccountDepositSignRouteImport } from './routes/account/deposit_/sign'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWithdrawRoute = AccountWithdrawRouteImport.update({
  id: '/account/withdraw',
  path: '/account/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDepositRoute = AccountDepositRouteImport.update({
  id: '/account/deposit',
  path: '/account/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionDetailsPositionIdIndexRoute =
  PositionDetailsPositionIdIndexRouteImport.update({
    id: '/position-details/$positionId/',
    path: '/position-details/$positionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PositionDetailsPositionIdOrderRoute =
  PositionDetailsPositionIdOrderRouteImport.update({
    id: '/position-details/$positionId/order',
    path: '/position-details/$positionId/order',
    getParentRoute: () => rootRouteImport,
  } as any)
const PositionDetailsPositionIdCloseRoute =
  PositionDetailsPositionIdCloseRouteImport.update({
    id: '/position-details/$positionId/close',
    path: '/position-details/$positionId/close',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountWithdrawSignRoute = AccountWithdrawSignRouteImport.update({
  id: '/account/withdraw_/sign',
  path: '/account/withdraw/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDepositSignRoute = AccountDepositSignRouteImport.update({
  id: '/account/deposit_/sign',
  path: '/account/deposit/sign',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/deposit': typeof AccountDepositRoute
  '/account/withdraw': typeof AccountWithdrawRoute
  '/account': typeof AccountIndexRoute
  '/account/deposit/sign': typeof AccountDepositSignRoute
  '/account/withdraw/sign': typeof AccountWithdrawSignRoute
  '/position-details/$positionId/close': typeof PositionDetailsPositionIdCloseRoute
  '/position-details/$positionId/order': typeof PositionDetailsPositionIdOrderRoute
  '/position-details/$positionId': typeof PositionDetailsPositionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/deposit': typeof AccountDepositRoute
  '/account/withdraw': typeof AccountWithdrawRoute
  '/account': typeof AccountIndexRoute
  '/account/deposit/sign': typeof AccountDepositSignRoute
  '/account/withdraw/sign': typeof AccountWithdrawSignRoute
  '/position-details/$positionId/close': typeof PositionDetailsPositionIdCloseRoute
  '/position-details/$positionId/order': typeof PositionDetailsPositionIdOrderRoute
  '/position-details/$positionId': typeof PositionDetailsPositionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account/deposit': typeof AccountDepositRoute
  '/account/withdraw': typeof AccountWithdrawRoute
  '/account/': typeof AccountIndexRoute
  '/account/deposit_/sign': typeof AccountDepositSignRoute
  '/account/withdraw_/sign': typeof AccountWithdrawSignRoute
  '/position-details/$positionId/close': typeof PositionDetailsPositionIdCloseRoute
  '/position-details/$positionId/order': typeof PositionDetailsPositionIdOrderRoute
  '/position-details/$positionId/': typeof PositionDetailsPositionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/deposit'
    | '/account/withdraw'
    | '/account'
    | '/account/deposit/sign'
    | '/account/withdraw/sign'
    | '/position-details/$positionId/close'
    | '/position-details/$positionId/order'
    | '/position-details/$positionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/deposit'
    | '/account/withdraw'
    | '/account'
    | '/account/deposit/sign'
    | '/account/withdraw/sign'
    | '/position-details/$positionId/close'
    | '/position-details/$positionId/order'
    | '/position-details/$positionId'
  id:
    | '__root__'
    | '/'
    | '/account/deposit'
    | '/account/withdraw'
    | '/account/'
    | '/account/deposit_/sign'
    | '/account/withdraw_/sign'
    | '/position-details/$positionId/close'
    | '/position-details/$positionId/order'
    | '/position-details/$positionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountDepositRoute: typeof AccountDepositRoute
  AccountWithdrawRoute: typeof AccountWithdrawRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountDepositSignRoute: typeof AccountDepositSignRoute
  AccountWithdrawSignRoute: typeof AccountWithdrawSignRoute
  PositionDetailsPositionIdCloseRoute: typeof PositionDetailsPositionIdCloseRoute
  PositionDetailsPositionIdOrderRoute: typeof PositionDetailsPositionIdOrderRoute
  PositionDetailsPositionIdIndexRoute: typeof PositionDetailsPositionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/withdraw': {
      id: '/account/withdraw'
      path: '/account/withdraw'
      fullPath: '/account/withdraw'
      preLoaderRoute: typeof AccountWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/deposit': {
      id: '/account/deposit'
      path: '/account/deposit'
      fullPath: '/account/deposit'
      preLoaderRoute: typeof AccountDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position-details/$positionId/': {
      id: '/position-details/$positionId/'
      path: '/position-details/$positionId'
      fullPath: '/position-details/$positionId'
      preLoaderRoute: typeof PositionDetailsPositionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position-details/$positionId/order': {
      id: '/position-details/$positionId/order'
      path: '/position-details/$positionId/order'
      fullPath: '/position-details/$positionId/order'
      preLoaderRoute: typeof PositionDetailsPositionIdOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position-details/$positionId/close': {
      id: '/position-details/$positionId/close'
      path: '/position-details/$positionId/close'
      fullPath: '/position-details/$positionId/close'
      preLoaderRoute: typeof PositionDetailsPositionIdCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/withdraw_/sign': {
      id: '/account/withdraw_/sign'
      path: '/account/withdraw/sign'
      fullPath: '/account/withdraw/sign'
      preLoaderRoute: typeof AccountWithdrawSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/deposit_/sign': {
      id: '/account/deposit_/sign'
      path: '/account/deposit/sign'
      fullPath: '/account/deposit/sign'
      preLoaderRoute: typeof AccountDepositSignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountDepositRoute: AccountDepositRoute,
  AccountWithdrawRoute: AccountWithdrawRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountDepositSignRoute: AccountDepositSignRoute,
  AccountWithdrawSignRoute: AccountWithdrawSignRoute,
  PositionDetailsPositionIdCloseRoute: PositionDetailsPositionIdCloseRoute,
  PositionDetailsPositionIdOrderRoute: PositionDetailsPositionIdOrderRoute,
  PositionDetailsPositionIdIndexRoute: PositionDetailsPositionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
