/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountWithdrawRouteImport } from './routes/account/withdraw'
import { Route as AccountDepositRouteImport } from './routes/account/deposit'
import { Route as PositionDetailsMarketIdIndexRouteImport } from './routes/position-details/$marketId/index'
import { Route as PositionDetailsMarketIdCloseRouteImport } from './routes/position-details/$marketId/close'
import { Route as PositionDetailsMarketIdAdjustMarginRouteImport } from './routes/position-details/$marketId/adjust-margin'
import { Route as AccountWithdrawSignRouteImport } from './routes/account/withdraw_/sign'
import { Route as AccountDepositSignRouteImport } from './routes/account/deposit_/sign'
import { Route as PositionDetailsMarketIdEditLeverageIndexRouteImport } from './routes/position-details/$marketId/edit-leverage_/index'
import { Route as OrderMarketIdSideIndexRouteImport } from './routes/order/$marketId/$side/index'
import { Route as PositionDetailsMarketIdEditSlTpSignRouteImport } from './routes/position-details/$marketId/edit-sl-tp_/sign'
import { Route as PositionDetailsMarketIdCloseSignRouteImport } from './routes/position-details/$marketId/close_/sign'
import { Route as PositionDetailsMarketIdCancelOrderSignRouteImport } from './routes/position-details/$marketId/cancel-order_/sign'
import { Route as PositionDetailsMarketIdAdjustMarginSignRouteImport } from './routes/position-details/$marketId/adjust-margin_/sign'
import { Route as OrderMarketIdSideSignRouteImport } from './routes/order/$marketId/$side/sign'
import { Route as OrderMarketIdSideIncreaseIndexRouteImport } from './routes/order/$marketId/$side/increase_/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWithdrawRoute = AccountWithdrawRouteImport.update({
  id: '/account/withdraw',
  path: '/account/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDepositRoute = AccountDepositRouteImport.update({
  id: '/account/deposit',
  path: '/account/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionDetailsMarketIdIndexRoute =
  PositionDetailsMarketIdIndexRouteImport.update({
    id: '/position-details/$marketId/',
    path: '/position-details/$marketId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PositionDetailsMarketIdCloseRoute =
  PositionDetailsMarketIdCloseRouteImport.update({
    id: '/position-details/$marketId/close',
    path: '/position-details/$marketId/close',
    getParentRoute: () => rootRouteImport,
  } as any)
const PositionDetailsMarketIdAdjustMarginRoute =
  PositionDetailsMarketIdAdjustMarginRouteImport.update({
    id: '/position-details/$marketId/adjust-margin',
    path: '/position-details/$marketId/adjust-margin',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountWithdrawSignRoute = AccountWithdrawSignRouteImport.update({
  id: '/account/withdraw_/sign',
  path: '/account/withdraw/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDepositSignRoute = AccountDepositSignRouteImport.update({
  id: '/account/deposit_/sign',
  path: '/account/deposit/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionDetailsMarketIdEditLeverageIndexRoute =
  PositionDetailsMarketIdEditLeverageIndexRouteImport.update({
    id: '/position-details/$marketId/edit-leverage_/',
    path: '/position-details/$marketId/edit-leverage/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrderMarketIdSideIndexRoute = OrderMarketIdSideIndexRouteImport.update({
  id: '/order/$marketId/$side/',
  path: '/order/$marketId/$side/',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionDetailsMarketIdEditSlTpSignRoute =
  PositionDetailsMarketIdEditSlTpSignRouteImport.update({
    id: '/position-details/$marketId/edit-sl-tp_/sign',
    path: '/position-details/$marketId/edit-sl-tp/sign',
    getParentRoute: () => rootRouteImport,
  } as any)
const PositionDetailsMarketIdCloseSignRoute =
  PositionDetailsMarketIdCloseSignRouteImport.update({
    id: '/position-details/$marketId/close_/sign',
    path: '/position-details/$marketId/close/sign',
    getParentRoute: () => rootRouteImport,
  } as any)
const PositionDetailsMarketIdCancelOrderSignRoute =
  PositionDetailsMarketIdCancelOrderSignRouteImport.update({
    id: '/position-details/$marketId/cancel-order_/sign',
    path: '/position-details/$marketId/cancel-order/sign',
    getParentRoute: () => rootRouteImport,
  } as any)
const PositionDetailsMarketIdAdjustMarginSignRoute =
  PositionDetailsMarketIdAdjustMarginSignRouteImport.update({
    id: '/position-details/$marketId/adjust-margin_/sign',
    path: '/position-details/$marketId/adjust-margin/sign',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrderMarketIdSideSignRoute = OrderMarketIdSideSignRouteImport.update({
  id: '/order/$marketId/$side/sign',
  path: '/order/$marketId/$side/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderMarketIdSideIncreaseIndexRoute =
  OrderMarketIdSideIncreaseIndexRouteImport.update({
    id: '/order/$marketId/$side/increase_/',
    path: '/order/$marketId/$side/increase/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/deposit': typeof AccountDepositRoute
  '/account/withdraw': typeof AccountWithdrawRoute
  '/account/': typeof AccountIndexRoute
  '/account/deposit/sign': typeof AccountDepositSignRoute
  '/account/withdraw/sign': typeof AccountWithdrawSignRoute
  '/position-details/$marketId/adjust-margin': typeof PositionDetailsMarketIdAdjustMarginRoute
  '/position-details/$marketId/close': typeof PositionDetailsMarketIdCloseRoute
  '/position-details/$marketId/': typeof PositionDetailsMarketIdIndexRoute
  '/order/$marketId/$side/sign': typeof OrderMarketIdSideSignRoute
  '/position-details/$marketId/adjust-margin/sign': typeof PositionDetailsMarketIdAdjustMarginSignRoute
  '/position-details/$marketId/cancel-order/sign': typeof PositionDetailsMarketIdCancelOrderSignRoute
  '/position-details/$marketId/close/sign': typeof PositionDetailsMarketIdCloseSignRoute
  '/position-details/$marketId/edit-sl-tp/sign': typeof PositionDetailsMarketIdEditSlTpSignRoute
  '/order/$marketId/$side/': typeof OrderMarketIdSideIndexRoute
  '/position-details/$marketId/edit-leverage/': typeof PositionDetailsMarketIdEditLeverageIndexRoute
  '/order/$marketId/$side/increase/': typeof OrderMarketIdSideIncreaseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/deposit': typeof AccountDepositRoute
  '/account/withdraw': typeof AccountWithdrawRoute
  '/account': typeof AccountIndexRoute
  '/account/deposit/sign': typeof AccountDepositSignRoute
  '/account/withdraw/sign': typeof AccountWithdrawSignRoute
  '/position-details/$marketId/adjust-margin': typeof PositionDetailsMarketIdAdjustMarginRoute
  '/position-details/$marketId/close': typeof PositionDetailsMarketIdCloseRoute
  '/position-details/$marketId': typeof PositionDetailsMarketIdIndexRoute
  '/order/$marketId/$side/sign': typeof OrderMarketIdSideSignRoute
  '/position-details/$marketId/adjust-margin/sign': typeof PositionDetailsMarketIdAdjustMarginSignRoute
  '/position-details/$marketId/cancel-order/sign': typeof PositionDetailsMarketIdCancelOrderSignRoute
  '/position-details/$marketId/close/sign': typeof PositionDetailsMarketIdCloseSignRoute
  '/position-details/$marketId/edit-sl-tp/sign': typeof PositionDetailsMarketIdEditSlTpSignRoute
  '/order/$marketId/$side': typeof OrderMarketIdSideIndexRoute
  '/position-details/$marketId/edit-leverage': typeof PositionDetailsMarketIdEditLeverageIndexRoute
  '/order/$marketId/$side/increase': typeof OrderMarketIdSideIncreaseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account/deposit': typeof AccountDepositRoute
  '/account/withdraw': typeof AccountWithdrawRoute
  '/account/': typeof AccountIndexRoute
  '/account/deposit_/sign': typeof AccountDepositSignRoute
  '/account/withdraw_/sign': typeof AccountWithdrawSignRoute
  '/position-details/$marketId/adjust-margin': typeof PositionDetailsMarketIdAdjustMarginRoute
  '/position-details/$marketId/close': typeof PositionDetailsMarketIdCloseRoute
  '/position-details/$marketId/': typeof PositionDetailsMarketIdIndexRoute
  '/order/$marketId/$side/sign': typeof OrderMarketIdSideSignRoute
  '/position-details/$marketId/adjust-margin_/sign': typeof PositionDetailsMarketIdAdjustMarginSignRoute
  '/position-details/$marketId/cancel-order_/sign': typeof PositionDetailsMarketIdCancelOrderSignRoute
  '/position-details/$marketId/close_/sign': typeof PositionDetailsMarketIdCloseSignRoute
  '/position-details/$marketId/edit-sl-tp_/sign': typeof PositionDetailsMarketIdEditSlTpSignRoute
  '/order/$marketId/$side/': typeof OrderMarketIdSideIndexRoute
  '/position-details/$marketId/edit-leverage_/': typeof PositionDetailsMarketIdEditLeverageIndexRoute
  '/order/$marketId/$side/increase_/': typeof OrderMarketIdSideIncreaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/deposit'
    | '/account/withdraw'
    | '/account/'
    | '/account/deposit/sign'
    | '/account/withdraw/sign'
    | '/position-details/$marketId/adjust-margin'
    | '/position-details/$marketId/close'
    | '/position-details/$marketId/'
    | '/order/$marketId/$side/sign'
    | '/position-details/$marketId/adjust-margin/sign'
    | '/position-details/$marketId/cancel-order/sign'
    | '/position-details/$marketId/close/sign'
    | '/position-details/$marketId/edit-sl-tp/sign'
    | '/order/$marketId/$side/'
    | '/position-details/$marketId/edit-leverage/'
    | '/order/$marketId/$side/increase/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/deposit'
    | '/account/withdraw'
    | '/account'
    | '/account/deposit/sign'
    | '/account/withdraw/sign'
    | '/position-details/$marketId/adjust-margin'
    | '/position-details/$marketId/close'
    | '/position-details/$marketId'
    | '/order/$marketId/$side/sign'
    | '/position-details/$marketId/adjust-margin/sign'
    | '/position-details/$marketId/cancel-order/sign'
    | '/position-details/$marketId/close/sign'
    | '/position-details/$marketId/edit-sl-tp/sign'
    | '/order/$marketId/$side'
    | '/position-details/$marketId/edit-leverage'
    | '/order/$marketId/$side/increase'
  id:
    | '__root__'
    | '/'
    | '/account/deposit'
    | '/account/withdraw'
    | '/account/'
    | '/account/deposit_/sign'
    | '/account/withdraw_/sign'
    | '/position-details/$marketId/adjust-margin'
    | '/position-details/$marketId/close'
    | '/position-details/$marketId/'
    | '/order/$marketId/$side/sign'
    | '/position-details/$marketId/adjust-margin_/sign'
    | '/position-details/$marketId/cancel-order_/sign'
    | '/position-details/$marketId/close_/sign'
    | '/position-details/$marketId/edit-sl-tp_/sign'
    | '/order/$marketId/$side/'
    | '/position-details/$marketId/edit-leverage_/'
    | '/order/$marketId/$side/increase_/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountDepositRoute: typeof AccountDepositRoute
  AccountWithdrawRoute: typeof AccountWithdrawRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountDepositSignRoute: typeof AccountDepositSignRoute
  AccountWithdrawSignRoute: typeof AccountWithdrawSignRoute
  PositionDetailsMarketIdAdjustMarginRoute: typeof PositionDetailsMarketIdAdjustMarginRoute
  PositionDetailsMarketIdCloseRoute: typeof PositionDetailsMarketIdCloseRoute
  PositionDetailsMarketIdIndexRoute: typeof PositionDetailsMarketIdIndexRoute
  OrderMarketIdSideSignRoute: typeof OrderMarketIdSideSignRoute
  PositionDetailsMarketIdAdjustMarginSignRoute: typeof PositionDetailsMarketIdAdjustMarginSignRoute
  PositionDetailsMarketIdCancelOrderSignRoute: typeof PositionDetailsMarketIdCancelOrderSignRoute
  PositionDetailsMarketIdCloseSignRoute: typeof PositionDetailsMarketIdCloseSignRoute
  PositionDetailsMarketIdEditSlTpSignRoute: typeof PositionDetailsMarketIdEditSlTpSignRoute
  OrderMarketIdSideIndexRoute: typeof OrderMarketIdSideIndexRoute
  PositionDetailsMarketIdEditLeverageIndexRoute: typeof PositionDetailsMarketIdEditLeverageIndexRoute
  OrderMarketIdSideIncreaseIndexRoute: typeof OrderMarketIdSideIncreaseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/withdraw': {
      id: '/account/withdraw'
      path: '/account/withdraw'
      fullPath: '/account/withdraw'
      preLoaderRoute: typeof AccountWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/deposit': {
      id: '/account/deposit'
      path: '/account/deposit'
      fullPath: '/account/deposit'
      preLoaderRoute: typeof AccountDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position-details/$marketId/': {
      id: '/position-details/$marketId/'
      path: '/position-details/$marketId'
      fullPath: '/position-details/$marketId/'
      preLoaderRoute: typeof PositionDetailsMarketIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position-details/$marketId/close': {
      id: '/position-details/$marketId/close'
      path: '/position-details/$marketId/close'
      fullPath: '/position-details/$marketId/close'
      preLoaderRoute: typeof PositionDetailsMarketIdCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position-details/$marketId/adjust-margin': {
      id: '/position-details/$marketId/adjust-margin'
      path: '/position-details/$marketId/adjust-margin'
      fullPath: '/position-details/$marketId/adjust-margin'
      preLoaderRoute: typeof PositionDetailsMarketIdAdjustMarginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/withdraw_/sign': {
      id: '/account/withdraw_/sign'
      path: '/account/withdraw/sign'
      fullPath: '/account/withdraw/sign'
      preLoaderRoute: typeof AccountWithdrawSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/deposit_/sign': {
      id: '/account/deposit_/sign'
      path: '/account/deposit/sign'
      fullPath: '/account/deposit/sign'
      preLoaderRoute: typeof AccountDepositSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position-details/$marketId/edit-leverage_/': {
      id: '/position-details/$marketId/edit-leverage_/'
      path: '/position-details/$marketId/edit-leverage'
      fullPath: '/position-details/$marketId/edit-leverage/'
      preLoaderRoute: typeof PositionDetailsMarketIdEditLeverageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$marketId/$side/': {
      id: '/order/$marketId/$side/'
      path: '/order/$marketId/$side'
      fullPath: '/order/$marketId/$side/'
      preLoaderRoute: typeof OrderMarketIdSideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position-details/$marketId/edit-sl-tp_/sign': {
      id: '/position-details/$marketId/edit-sl-tp_/sign'
      path: '/position-details/$marketId/edit-sl-tp/sign'
      fullPath: '/position-details/$marketId/edit-sl-tp/sign'
      preLoaderRoute: typeof PositionDetailsMarketIdEditSlTpSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position-details/$marketId/close_/sign': {
      id: '/position-details/$marketId/close_/sign'
      path: '/position-details/$marketId/close/sign'
      fullPath: '/position-details/$marketId/close/sign'
      preLoaderRoute: typeof PositionDetailsMarketIdCloseSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position-details/$marketId/cancel-order_/sign': {
      id: '/position-details/$marketId/cancel-order_/sign'
      path: '/position-details/$marketId/cancel-order/sign'
      fullPath: '/position-details/$marketId/cancel-order/sign'
      preLoaderRoute: typeof PositionDetailsMarketIdCancelOrderSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position-details/$marketId/adjust-margin_/sign': {
      id: '/position-details/$marketId/adjust-margin_/sign'
      path: '/position-details/$marketId/adjust-margin/sign'
      fullPath: '/position-details/$marketId/adjust-margin/sign'
      preLoaderRoute: typeof PositionDetailsMarketIdAdjustMarginSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$marketId/$side/sign': {
      id: '/order/$marketId/$side/sign'
      path: '/order/$marketId/$side/sign'
      fullPath: '/order/$marketId/$side/sign'
      preLoaderRoute: typeof OrderMarketIdSideSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$marketId/$side/increase_/': {
      id: '/order/$marketId/$side/increase_/'
      path: '/order/$marketId/$side/increase'
      fullPath: '/order/$marketId/$side/increase/'
      preLoaderRoute: typeof OrderMarketIdSideIncreaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountDepositRoute: AccountDepositRoute,
  AccountWithdrawRoute: AccountWithdrawRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountDepositSignRoute: AccountDepositSignRoute,
  AccountWithdrawSignRoute: AccountWithdrawSignRoute,
  PositionDetailsMarketIdAdjustMarginRoute:
    PositionDetailsMarketIdAdjustMarginRoute,
  PositionDetailsMarketIdCloseRoute: PositionDetailsMarketIdCloseRoute,
  PositionDetailsMarketIdIndexRoute: PositionDetailsMarketIdIndexRoute,
  OrderMarketIdSideSignRoute: OrderMarketIdSideSignRoute,
  PositionDetailsMarketIdAdjustMarginSignRoute:
    PositionDetailsMarketIdAdjustMarginSignRoute,
  PositionDetailsMarketIdCancelOrderSignRoute:
    PositionDetailsMarketIdCancelOrderSignRoute,
  PositionDetailsMarketIdCloseSignRoute: PositionDetailsMarketIdCloseSignRoute,
  PositionDetailsMarketIdEditSlTpSignRoute:
    PositionDetailsMarketIdEditSlTpSignRoute,
  OrderMarketIdSideIndexRoute: OrderMarketIdSideIndexRoute,
  PositionDetailsMarketIdEditLeverageIndexRoute:
    PositionDetailsMarketIdEditLeverageIndexRoute,
  OrderMarketIdSideIncreaseIndexRoute: OrderMarketIdSideIncreaseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
